services:
  nginx: &nginx
    volumes:
      - ./html_contents/:/usr/share/nginx/html
  publify: &publify
    stdin_open: true
    tty: true
    volumes:
      - ./themes/:/rails_app/themes
      - ./files/:/rails_app/public/files
  mad-wiki: &mad-wiki
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./wiki_data/data/:/ext/
  mysql: &mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local
  wiki_data:
    driver: local
