version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1.0.0
    ports:
      - '8080:80'
      - '443:443'
    depends_on:
      - nginx
    links:
      - nginx
    restart: always
    environment:
      DOMAINS: 'babanba-n.iobb.net -> http://nginx'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'
  nginx: &nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - "html_data:/usr/share/nginx/html"
      - "./init/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - publify
    links:
      - publify
  publify: &publify
    build:
      context: .
      dockerfile: ./docker/publify/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "themes:/rails_app/themes"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      RAILS_ENV: production
  mysql: &mysql
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - "./init/initdb.d/:/docker-entrypoint-initdb.d"
      - "mysql-db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: publify
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  mysql-db:
    driver_opts:
      type: none
      device: /home/vagrant/docker/data/mysql
      o: bind
  html_data:
    driver_opts:
      type: none
      device: /var/site/skyscraper/html_contents 
      o: bind
  themes:
    driver_opts:
      type: none
      device: /var/site/skyscraper/themes
      o: bind
