version: '3.1'
services:
  nginx: &nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - "./init/:/etc/nginx/conf.d/"
    ports:
      - "80:80"
    depends_on:
      - publify
    links:
      - publify
  publify: &publify
    build:
      context: .
      dockerfile: ./docker/publify/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./themes/:/rails_app/themes"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      RAILS_ENV: production
  mysql: &mysql
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - "./init/initdb.d/:/docker-entrypoint-initdb.d"
      - "./mysql_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: publify
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  mysql_data:
    driver: local
