services:
  nginx: &nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - publify
      - mad-wiki-nginx
    links:
      - publify
      - mad-wiki-nginx
  publify: &publify
    build:
      context: .
      dockerfile: ./docker/publify/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      RAILS_ENV: production
      BUILDPLATFORM: "x86_64"
    logging:
      driver: "json-file" # defaults if not specified
      options:
        max-size: 10m
        max-file: "3"
  mad-wiki-nginx: &mad-wiki-nginx
    build:
      context: .
      dockerfile: ./docker/mad_wiki_nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mad-wiki
    links:
      - mad-wiki
  mad-wiki: &mad-wiki
    build:
      context: .
      dockerfile: ./docker/mad_wiki/Dockerfile
    ports:
      - "9000:9000"
    logging:
      driver: "json-file" # defaults if not specified
      options:
        max-size: 10m
        max-file: "3"
  mysql: &mysql
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --max_allowed_packet=32M
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: publify
      MYSQL_ROOT_PASSWORD: svc2027
      MYSQL_USER: baban
      MYSQL_PASSWORD: svc2027
