login: &login
  adapter: mysql2
  host: mysql
  username: root
  password: root

development:
  database: digital_root_hub_dev
  <<: *login

test:
  database: digital_root_hub_test
  <<: *login

production:
  database: digital_root_hub
  <<: *login
