---
apiVersion: v1
kind: Service
metadata:
  name: digital-root-hub
spec:
  type: LoadBalancer
  ports:
  - name: "digital-root-hub-port"
    protocol: 'TCP'
    port: 3000
    targetPort: 3000
  selector:
    app: skyscraper-app
