---
apiVersion: v1
kind: Service
metadata:
  name: skyscraper-service
spec:
  type: LoadBalancer
  ports:
    - name: 'http-port'
      protocol: 'TCP'
      port: 80
      targetPort: 80
    - name: 'https-port'
      protocol: 'TCP'
      port: 443
      targetPort: 80
  selector:
    app: skyscraper-app
