---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyscraper-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skyscraper-app
  template:
    metadata:
      labels:
        app: skyscraper-app
    spec:
      containers:
        - name: skyscraper-nginx
          image: localhost:5000/skyscraper_nginx
          ports:
            - containerPort: 80
