---
apiVersion: v1
kind: Service
metadata:
  name: publify
spec:
  type: ClusterIP
  ports:
  - name: "publify-port"
    protocol: 'TCP'
    port: 3000
    targetPort: 3000
  selector:
    app: skyscraper-app
