---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skyscraper-app
  template:
    metadata:
      labels:
        app: skyscraper-app
    spec:
      containers:
        - name: skyscraper-publify
          image: babanban/skyscraper_publifyy
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: "production"
