apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-pod
spec:
  serviceName: mysql-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: skyscraper-app
  template:
    metadata:
      labels:
        app: skyscraper-app
    spec:
      containers:
        - name: mysql-container
          image: mysql:5.7.22
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: mysqldata
            mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              value: publify
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
  volumeClaimTemplates:
  - metadata:
      name: mysqldata
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
  - name: "mysql-port"
    protocol: 'TCP'
    port: 3306
    targetPort: 3306
  selector:
    app: skyscraper-app
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: digital-root-hub
spec:
  type: ClusterIP
  ports:
  - name: "digital-root-hub-port"
    protocol: 'TCP'
    port: 3000
    targetPort: 3000
  selector:
    app: skyscraper-app
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: publify
spec:
  type: ClusterIP
  ports:
  - name: "publify-port"
    protocol: 'TCP'
    port: 3000
    targetPort: 3000
  selector:
    app: skyscraper-app
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-root-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skyscraper-app
  template:
    metadata:
      labels:
        app: skyscraper-app
    spec:
      containers:
        - name: skyscraper-digital-root-hub
          image: babanban/skyscraper_digital_root_hub
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skyscraper-app
  template:
    metadata:
      labels:
        app: skyscraper-app
    spec:
      containers:
        - name: skyscraper-publify
          image: babanban/skyscraper_publifyy
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyscraper-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skyscraper-app
  template:
    metadata:
      labels:
        app: skyscraper-app
    spec:
      containers:
        - name: skyscraper-nginx
          image: babanban/skyscraper_nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: skyscraper-service
spec:
  type: LoadBalancer
  ports:
    - name: 'http-port'
      protocol: 'TCP'
      port: 80
      targetPort: 80
    - name: 'https-port'
      protocol: 'TCP'
      port: 443
      targetPort: 80
  selector:
    app: skyscraper-app
